apiVersion: v1
kind: ConfigMap
metadata:
  name: orgtype-config
  namespace: orgtype
data:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: orgtype
  DB_USER: orgtype
  ORG_SERVICE_URL: http://org-service:8081
  GAME_SERVICE_URL: http://game-service:8082
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: orgtype
type: Opaque
stringData:
  DB_PASS: orgtype
  POSTGRES_PASSWORD: orgtype
